src/main/java/ch/rootlogin/hftm/blog/models/Comment.java
package ch.rootlogin.hftm.blog.models;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity
public class Comment extends CreatableEntity {
	@Id
	@GeneratedValue
	private long id;

	private String content;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "post_id")
	private Post post;

	protected Comment() {}

	public Comment(final String content) {
		this.content = content;
	}

	public long getId() {
		return id;
	}

	public String getContent() {
		return content;
	}

	public Post getPost() {
		return post;
	}

	public void setPost(final Post post) {
		this.post = post;
	}
}

src/main/java/ch/rootlogin/hftm/blog/models/CreatableEntity.java
package ch.rootlogin.hftm.blog.models;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;

@MappedSuperclass
public abstract class CreatableEntity {
	@Column
	private LocalDateTime createdAt;

	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(final LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	@PreUpdate
	@PrePersist
	public void updateCreatedAt() {
		final LocalDateTime now = LocalDateTime.now();
		if (getCreatedAt() == null) {
			setCreatedAt(now);
		}
	}
}

src/main/java/ch/rootlogin/hftm/blog/models/Post.java
package ch.rootlogin.hftm.blog.models;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

@Entity
public class Post extends CreatableEntity {
	@Id
	@GeneratedValue
	private long id;

	private String title;
	private String content;

	@OneToMany(mappedBy = "post", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	private List<Comment> comments = new ArrayList<>();

	protected Post() {
	}

	public Post(final String title, final String content) {
		this.title = title;
		this.content = content;
	}

	public long getId() {
		return id;
	}

	public String getTitle() {
		return title;
	}

	public String getContent() {
		return content;
	}

	public void addComment(final Comment comment) {
		comments.add(comment);
		comment.setPost(this);
	}

	public Iterable<Comment> getComments() {
		return comments;
	}

	public boolean hasComments() {
		return !comments.isEmpty();
	}

	public Optional<Comment> getLatestComment() {
		if (comments.isEmpty()) {
			return Optional.empty();
		}
		return comments.stream().max((c1, c2) -> c1.getCreatedAt().compareTo(c2.getCreatedAt()));
	}

	@Override
	public String toString() {
		return "Post " + getId() + ", title " + getTitle();
	}
}

src/main/java/ch/rootlogin/hftm/blog/models/repo/CommentRepository.java
package ch.rootlogin.hftm.blog.models.repo;

import javax.enterprise.context.RequestScoped;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.Transactional;

import ch.rootlogin.hftm.blog.models.Comment;
import ch.rootlogin.hftm.blog.models.Post;

@RequestScoped
public class CommentRepository
{
	@PersistenceContext
	private EntityManager em;

	@Transactional
	public void persist(final Long postId, final Comment c) {
		final Post post = em.find(Post.class, postId);
		final Comment comment = em.merge(c);
		post.addComment(comment);
		em.persist(post);
	}
}

src/main/java/ch/rootlogin/hftm/blog/models/repo/PostRepository.java
package ch.rootlogin.hftm.blog.models.repo;

import java.util.Optional;

import javax.enterprise.context.RequestScoped;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import ch.rootlogin.hftm.blog.models.Post;

@RequestScoped
public class PostRepository {
	@PersistenceContext
	private EntityManager em;

	public Iterable<Post> findAll() {
		return em.createQuery("SELECT p FROM Post p", Post.class).getResultList();
	}

	public Optional<Post> find(final Long id) {
		return Optional.ofNullable(em.find(Post.class, id));
	}
}

src/main/java/ch/rootlogin/hftm/blog/controller/BaseController.java
package ch.rootlogin.hftm.blog.controller;

import java.util.Map;
import java.util.Optional;

import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.context.FacesContext;

public abstract class BaseController {
	protected Optional<String> getParameter(final String name) {
		final Map<String, String> params =
				FacesContext.getCurrentInstance()
						.getExternalContext()
						.getRequestParameterMap();
		return Optional.ofNullable(params.get(name));
	}

	protected void addMessage(final Severity severity, final String message) {
		final FacesContext context = FacesContext.getCurrentInstance();
		context.addMessage(
				null, new FacesMessage(severity, message, null));
		context.getExternalContext().getFlash().setKeepMessages(true);
	}

	protected String redirect(final String page) {
		final String separator = page.contains("?") ? "&" : "?";
		return page + separator + "faces-redirect=true&includeViewParams=true";
	}
}

src/main/java/ch/rootlogin/hftm/blog/controller/CommentController.java
package ch.rootlogin.hftm.blog.controller;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import ch.rootlogin.hftm.blog.models.Comment;
import ch.rootlogin.hftm.blog.models.Post;
import ch.rootlogin.hftm.blog.models.repo.CommentRepository;

@Named
@RequestScoped
public class CommentController extends BaseController
{
	@Inject
	private CommentRepository repo;

	@NotNull(message = "Gib bitte einen Kommentar ein!")
	@Size(min = 5, message = "Ein Kommentar hat mind. 5 Zeichen!")
	private String content;

	public String getContent()
	{
		return content;
	}

	public void setContent(final String content)
	{
		this.content = content;
	}

	public String save(final Post p)
	{
		repo.persist(p.getId(), new Comment(getContent()));
		addMessage(FacesMessage.SEVERITY_INFO, "Der Kommentar wurde gespeichert!");
		return redirect(PostController.POST_PAGE + "?id=" + p.getId());
	}
}

src/main/java/ch/rootlogin/hftm/blog/controller/PostController.java
package ch.rootlogin.hftm.blog.controller;

import java.util.Optional;

import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;

import ch.rootlogin.hftm.blog.models.Post;
import ch.rootlogin.hftm.blog.models.repo.PostRepository;

@Named
@RequestScoped
public class PostController extends BaseController
{
	public static final String POSTS_PAGE = "index.xhtml";
	public static final String POST_PAGE = "post.xhtml";

	@Inject
	private PostRepository repo;

	private Optional<Post> currentPost;

	public String getPostId()
	{
		final Optional<String> idOrNothing = getParameter("id");
		return idOrNothing.isPresent()
				? idOrNothing.get()
				: "";
	}

	public String getPostsPage()
	{
		return POSTS_PAGE;
	}

	public String getPostPage()
	{
		return POST_PAGE;
	}

	public Iterable<Post> getPosts()
	{
		return repo.findAll();
	}

	public Optional<Long> parsePostId()
	{
		try
		{
			return Optional.of(Long.parseLong(getPostId()));
		}
		catch (final NumberFormatException nfe)
		{
			addMessage(FacesMessage.SEVERITY_ERROR, "Falsche Post ID.");
			return Optional.empty();
		}
	}

	public String checkWhetherPostExists()
	{
		findCurrentPost();
		if (!currentPost.isPresent())
		{
			addMessage(FacesMessage.SEVERITY_ERROR, "Post nicht gefunden.");
			return getPostsPage();
		}
		return null;
	}

	private void findCurrentPost()
	{
		if (currentPost != null)
		{
			return;
		}
		currentPost = Optional.empty();
		final Optional<Long> postIdOrNothing = parsePostId();
		if (postIdOrNothing.isPresent())
		{
			currentPost = repo.find(postIdOrNothing.get());
		}
	}

	public Post getCurrentPost()
	{
		findCurrentPost();
		if (currentPost == null || !currentPost.isPresent())
		{
			return new Post("Post wurde nicht gefunden", "Kein Inhalt");
		}
		return currentPost.get();
	}
}

src/main/java/ch/rootlogin/hftm/blog/controller/QuoteOfTheDayController.java
package ch.rootlogin.hftm.blog.controller;

import javax.inject.Named;
import java.util.Random;

@Named
public class QuoteOfTheDayController {

    public static final String[] QUOTES = {
            "Woah, voll Gängster!",
            "Ey, wie krass!",
            "JavaEE 4 Winners!",
            "Chrömli si fein.",
            "Das geid ab!"
    };

    public String say() {
        int rnd = new Random().nextInt(QUOTES.length);

        return QUOTES[rnd];
    }
}

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:rootlogin="http://rootlogin.ch/facelets">

	<ui:composition template="/WEB-INF/includes/layout.xhtml">
		<ui:define name="title">Mein Blog</ui:define>
		<ui:define name="content">
			<h1>Mein Blog</h1>
			<ui:repeat value="#{postController.posts}" var="post">
				<article>
					<h3><h:outputText value="#{post.title}" /></h3>
					<small><rootlogin:date date="#{post.createdAt}" /></small>
					<p>
						<h:outputText value="#{post.content}" />
					</p>
					<p>
						<small>
							#{post.comments.size()} Kommentar#{post.comments.size() == 1 ? '' : 'e'}
							-
							<h:outputLink value="#{postController.postPage}">
								<f:param name="id" value="#{post.id}" />
								<h:outputText value="Mehr lesen" />
							</h:outputLink>
						</small>
					</p>
					<hr />
				</article>
			</ui:repeat>
		</ui:define>
	</ui:composition>
</html>

src/main/webapp/post.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:rootlogin="http://rootlogin.ch/facelets">

<f:metadata>
	<f:viewAction action="#{postController.checkWhetherPostExists}"
		onPostback="true" />
</f:metadata>

<ui:composition template="/WEB-INF/includes/layout.xhtml">
	<ui:define name="title">Mein Blog :: #{postController.currentPost.title}</ui:define>
	<ui:define name="content">
		<h1>#{postController.currentPost.title}</h1>
		<small>
			<rootlogin:date date="#{postController.currentPost.createdAt}" />
		</small>
		<p>
			<h:outputText value="#{postController.currentPost.content}" />
		</p>
		<hr />
		<h3>Kommentare</h3>
		<ui:repeat value="#{postController.currentPost.comments}"
			var="comment">
			<div class="card">
				<div class="card-body">
					#{comment.content}
					<small class="comment-footer">
						<rootlogin:date date="#{comment.createdAt}" />
					</small>
				</div>
			</div>
		</ui:repeat>
		<hr />
		<h:form id="addComment">
			<div class="form-group #{yourComment.valid ? '' : 'has-error'}">
				<label for="yourComment" class="sr-only">Dein Kommentar</label>
				<h:inputText value="#{commentController.content}"
					binding="#{yourComment}" p:placeholder="Dein Kommentar"
					class="form-control" id="yourComment" />
				<h:messages class="help-block" id="messageYourComment"
					for="yourComment" />
			</div>
			<h:commandButton value="Kommentar hinzufügen"
				action="#{commentController.save(postController.currentPost)}"
				class="btn btn-primary" includeViewParams="true">
				<f:param name="id" value="#{postController.postId}" />
			</h:commandButton>
		</h:form>
		<hr />
		<h:outputLink value="#{postController.postsPage}">
			<h:outputText value="Zurück zu den Posts" />
		</h:outputLink>
	</ui:define>
</ui:composition>

</html>